sudo -u postgres psql

CREATE USER birchett WITH PASSWORD 'Birchett_Fellow228'; 
REVOKE ALL ON SCHEMA public FROM birchett; 
GRANT USAGE ON SCHEMA public TO birchett;
REVOKE ALL ON DATABASE ihdb FROM birchett; 

\c ihdb

-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ma_table TO birchett;
GRANT SELECT ON TABLE chws_data TO birchett;
GRANT SELECT ON TABLE chws TO birchett;
GRANT SELECT ON TABLE districts TO birchett;
GRANT SELECT ON TABLE families TO birchett;
GRANT SELECT ON TABLE patients TO birchett;
GRANT SELECT ON TABLE sites TO birchett;
GRANT SELECT ON TABLE zones TO birchett;


sudo adduser birchett


-- sudo passwd birchett
-- sudo usermod -aG sudo birchett






sudo -u postgres psql

CREATE USER alafia WITH PASSWORD 'alafia_Afrikdigital2025'; 


CREATE DATABASE alafia_db WITH ENCODING 'UTF8' TEMPLATE=template0;
CREATE DATABASE alafia_db WITH ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE=template0;

GRANT ALL PRIVILEGES ON DATABASE alafia_db TO alafia;
GRANT ALL ON SCHEMA public TO alafia;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO alafia;
GRANT ALL PRIVILEGES ON SCHEMA public TO alafia;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE alertes TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE assurance_produits TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE assurances TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE caisses TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE categories TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE centres TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE commandes TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE compte_bancaires TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE correction_stocks TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE depenses TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE directions TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE droit_profils TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE droits TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE entrees TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE factures TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE failed_jobs TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE fournisseurs TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE initialisations TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE inventaires TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE magasins TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE migrations TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE mouvement_caisses TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE mouvement_sis TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE mouvements TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE mutuelles TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE observations TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE operation_bancaires TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE password_resets TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE patients TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE personal_access_tokens TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_commandes TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_correction_stocks TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_entrees TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_factures TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_inventaires TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_reception_ds TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_reception_sis TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_receptions TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_sorties TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_transfert_dps TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_transfert_ds TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_transfert_sis TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_transferts TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produit_ventes TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE produits TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profil_users TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profils TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reception_ds TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reception_sis TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE receptions TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reclamations TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reglements TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ruptures TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE societies TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sorties TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stock_produits TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stock_sis TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stocks TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE transfert_ds TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE transferts TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE type_categories TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE usercons TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE validations TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE valider_commande_controllers TO alafia;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ventes TO alafia;
